name: flutter_demo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0

  dio: 4.0.4
  retrofit: ^3.0.1

  get_it: 7.2.0
  injectable: ^1.5.3

  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.2

  intl: ^0.17.0
  flutter_markdown: ^0.6.9
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  freezed: ^1.1.0
  json_serializable: ^6.1.2
  retrofit_generator: any
  injectable_generator: ^1.5.3

dependency_overrides:
  test_api: 0.4.9

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
