name: flutter_demo
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  dio: ^5.3.2
  retrofit: ^4.0.1

  get_it: ^8.0.2
  injectable: ^2.3.0

  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3

  intl: ^0.19.0
  flutter_markdown: ^0.7.4+1
  url_launcher: ^6.1.12
  mocktail: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.4.0

dependency_overrides:
  test_api: ^0.6.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
